# Generated by Django 3.1.7 on 2023-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightListModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=50)),
                ('flight_no', models.CharField(max_length=250)),
                ('ticket_price', models.CharField(max_length=50)),
                ('ava_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('dep_place', models.CharField(blank=True, max_length=50, null=True)),
                ('dep_time', models.TimeField()),
                ('des_place', models.CharField(blank=True, max_length=50, null=True)),
                ('des_time', models.TimeField()),
                ('travel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel_fee', models.CharField(max_length=50)),
                ('allowed_wght', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
