# Generated by Django 3.1.7 on 2023-05-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_flightlistmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_products',
            new_name='total_tickets',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_names',
        ),
        migrations.AddField(
            model_name='order',
            name='flight_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.flightlistmodels'),
        ),
        migrations.AlterField(
            model_name='flightlistmodels',
            name='ava_seats',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
    ]
