# Generated by Django 3.1.7 on 2023-06-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20230520_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flight_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flightorder', to='order.flightlistmodels'),
        ),
        migrations.CreateModel(
            name='seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flightbook', to='order.flightlistmodels')),
            ],
        ),
    ]
