# Generated by Django 3.1.7 on 2023-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=100),
        ),
    ]
